### ISSUE TITLE
Change output section in the README

### ISSUE THREAD

**Issue by anotherbridge** [Neo23x0/yaraQA#2]
**Problem:**

The following part of the output section in the README file is not valid for the current version: 
> yaraQA writes the detected issues to a file named `yaraQA-issues.txt` by default. If you select `--json` it'll be written to `yaraQA-issues.json`.

There are two issues with the description: 
1. By default there is not `yaraQA-issues.txt` written by default. If the outfile flag is used the standard output format is JSON. 
2. There is no argument `--json` declared in the argument parser.

**Comment by Neo23x0** [comment]
Yeah, I first thought I'd support both output formats and later decided against it.
