### ISSUE TITLE
Consider reducing level of MO1 to 'informational' or refactoring to only match certain modules.

### ISSUE THREAD

**Issue by tlansec** [Neo23x0/yaraQA#3]
The sparing use of module does not necessarily impact performance at runtime and shouldn't be considered critical to performance.

For example the `math` and `hash` modules do not pre-calculate any values and refactoring rules based on their limited appearance in your ruleset will not improve performance.

I guess the spirit of this rule was aimed at the `pe` and `dotnet` modules which do populate a number of fields regardless of whether they are checked in the rule condition.

**Comment by Neo23x0** [comment]
I already made these changes locally but didn't commit them. It's exactly what I did. Thanks!

![Screenshot 2023-02-14 at 00 17 53](https://user-images.githubusercontent.com/2851492/218596397-85898a5b-c82c-4617-8d11-ffc1fbd7a129.png)
![Screenshot 2023-02-14 at 00 18 01](https://user-images.githubusercontent.com/2851492/218596401-5a1c2620-4458-4955-b79e-ea7004153c5e.png)

**Comment by Neo23x0** [comment]
fixed in https://github.com/Neo23x0/yaraQA/commit/7afd1cff47dc73de2e30c467af9b47e6c97a5434
